---
title: "Platic pollution and health"
output: 
    html_document:
       toc: yes
       toc_float: yes
       md_keep: yes
       theme: flatly
       code_folding: hide
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(pacman)
p_load(readtext, quanteda, tidytext, here, tidyverse, DT, myScrapers, europepmc, tidypmc, kableExtra, quanteda.textstats, quanteda.textplots, ggraph, igraph, tidygraph)
```

## Govt enquiry into plastic pollution

```{r}

## import pdfs

path <- here("docs")
pdfs <- list.files(path, "pdf", full.names = T)
docs <- map(pdfs, readtext)
docs

```

### 

### Report conclusions and recommendations:

<https://publications.parliament.uk/pa/cm201617/cmselect/cmenvaud/179/17908.htm?utm_source=179&utm_medium=crbullet&utm_campaign=modulereports>

```{r}

docs[[1]] %>%
  #(str_detect(text, "Conclusions")) %>%
  select(text) %>%
  knitr::kable()



```

### Govt. response

```{r}

docs[[2]] %>%
  #(str_detect(text, "Conclusions")) %>%
  select(text) %>%
  knitr::kable()

```

### What is the impact on human health?

### Split docs into paragraphs

```{r}

para_1 <- docs[[1]] %>%
  unnest_tokens("para", text, "paragraphs")

para_2 <- docs[[2]] %>%
  unnest_tokens("para", text, "paragraphs")

```

## Find mentions of 'health'

### Report:

```{r}

health_1 <- para_1 %>%
  filter(str_detect(para, "health"))

health_1 %>%
  knitr::kable(cwidth = 8)

```

### Response:

```{r}

health_2 <- para_2 %>%
  filter(str_detect(para, "health"))

health_2 %>%
  knitr::kable(cwidth = 8)

```

## Face masks and plastic pollution

```{r, cache=TRUE}

search <- "(face masks OR plastic) pollution public health human[mh] review"

start <- 2000
end <- 2021

n <- 203
key <- Sys.getenv("ncbi_key")

res <- pubmedAbstractR(search = search, n = n , start = start, end = end, ncbi_key = key, authors = F)

res$abstracts$title

selected <- c(1, 3, 6, 10, 14, 16, 18, 32, 33, 39, 63, 66, 69, 75, 76, 87, 95, 99, 107, 113, 119, 123, 144, 160, 185, 188, 196)

res <- res$abstracts %>%
  mutate(id = row_number())

res_selected <- res %>%
  filter(id %in% selected)
```

```{r}

corp <- corpus(res, text_field = "abstract")

toks <- corp %>% tokens(remove_punct = T, remove_symbols = T, remove_numbers = T, remove_url = T) %>% tokens_tolower() %>% tokens_wordstem() %>%
  quanteda::tokens_remove(stopwords("english")) 
dfm <- toks %>%
  dfm()

fcm <- fcm(toks)
feat <- names(topfeatures(fcm, 50))
x <- fcm_select(fcm, pattern = feat) 

x %>%
    textplot_network(min_freq = 0.8, omit_isolated = T)

dfm %>%
  data.frame() %>%
  tidygraph::as_tbl_graph() %>%
  ggraph(layout = "fr") +
  geom_edge_link() +
  geom_node_point(aes(label = name)) 

summary(dfm)
cor <- quanteda.textstats::textstat_simil(dfm)

textstat_collocations(toks) %>%
  data.frame() |>
arrange(-count)

cor %>%
  data.frame() %>%
  filter(abs(correlation) > 0.3)

textplot_network(dfm)
```



```{r}
res$abstracts %>%
  filter(journal ==  "Sci Total Environ") %>%
  select(year, pmid, title) %>%
  distinct() %>%
  mutate(select = 0) %>%
  DT::datatable(editable = TRUE, filter = "top", 
                extensions = 'Buttons', options = list(pageLength = 25, dom = 'Bfrtip', buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
  ))



```

```{r, cache=TRUE}

details <- map(res_selected$pmid, epmc_details) %>%
  map(., "basic") %>%
  map(., possibly("pmcid", otherwise = NA_real_)) %>%
  as.character()
  
details <- details[details %>%
  str_detect(., "^PMC")]
  

ft <- map(details, pmc_xml)
ftext <- map(ft, pmc_text)

ft_refs <- map(ft, pmc_reference)
ft_meta <- map(ft, pmc_metadata)

ft_meta %>%
  enframe() %>%
  unnest_auto("value") %>%
  knitr::kable() %>%
  kableExtra::kable_classic_2()



```

```{r}

ft_table <- map(ft, pmc_table)
ft_table

```



## Country level estimates of volume of plastic pollution from PPE/face masks

After @Chowdhury2021

```{r, eval = FALSE}

ft_table[[17]][4] %>%
  knitr::kable() %>%
  kableExtra::kable_styling()

```



## References
